#!/bin/bash

declare -A sue

sue=([children]=3 [cats]=7 [samoyeds]=2 [pomeranians]=3 [akitas]=0
     [vizslas]=0 [goldfish]=5 [trees]=3 [cars]=2 [perfumes]=1)

while read _ num key0 val0 key1 val1 key2 val2; do
    num=${num%:}
    key0=${key0%:}
    val0=${val0%,}
    key1=${key1%:}
    val1=${val1%,}
    key2=${key2%:}

    if (( sue[$key0] == val0 &&
          sue[$key1] == val1  &&
          sue[$key2] == val2 )); then
        echo "The correct Sue is number $num."
        break
    fi
done < input
