#!/bin/bash

# Calculate prime numbers up to argument (Sieve of Eratosthenes)
# Put result into global array "primes"
get_primes () {
    local num="$1"
    local sqrt=$(bc <<< "sqrt($1)")
    local idx
    local i
    for i in $(seq 0 $num); do
        idx[i]=1
    done
    for i in $(seq 2 $sqrt); do
        if (( idx[i] )); then
            for (( j = i**2; j <= num; j += i )); do
                idx[$j]=0
            done
        fi
    done

    for (( i = 2; i < ${#idx[@]}; ++i )); do
        if (( idx[i] )); then
            primes+=($i)
        fi
    done
}

# For a given number, get the prime factor decomposition
# Write prime factors into associative array of prime factors (keys) and their power (values)
get_prime_factors () {
    local num="$1"
    local prime
    for prime in "${primes[@]}"; do

        if (( prime ** 2 > num )); then
            break
        fi
        while (( num % prime == 0 )); do
            (( ++prime_factors[$prime] ))
            (( num /= prime ))
        done
    done
    if (( num > 1 )); then
        (( ++prime_factors[$num] ))
    fi
}

# Calculate sum of divisors via prime factors
get_sigma () {
    local num="$1"
    declare -A prime_factors
    get_prime_factors "$1"
    local factor
    local sigma=1
    for factor in "${!prime_factors[@]}"; do
        (( sigma *= (factor ** (prime_factors[$factor] + 1) - 1) / (factor - 1) ))
    done
    echo "$sigma"
}

# Script starts here
min_pres=$(< input)
(( min_pres /= 10 ))    # Every elf leaves 10 presents

get_primes 2000         # Pre-calculate primes up to 2000 (won't need any more)

step=100000             # Big steps between houses at first
start=100000            # Start at this house

lasthouse=$min_pres     # Must be higher than the first house we find

# Repeate this until the step is 1 and we find a house
while (( step >= 1 )); do
    for (( house = start; sigma < min_pres; house += step )); do

        # Get number of presents for this house
        sigma=$(get_sigma $house)

        # If we previously found a house with a lower number, we're past it now
        if (( house > lasthouse )); then
            echo "House count higher than with bigger step, skipping..."
            break
        fi
    done

    # Remember house number where we found enough presents
    lasthouse=$(( house - step ))

    printf "Stepsize: %7d, first house: %8d\n" $step $lasthouse

    # Half the step for next round
    (( step /= 2 ))

    # Start at with a number 3/4 of what we know to have enough presents
    (( start = house / 4 * 3 ))

    # Reset this because the loop condition checks it
    sigma=0
done
