#!/usr/bin/env ruby

search = File.open(ARGV[0]).readlines(chomp: true).map(&:chars)
range_y = (0...search.size)
range_x = (0...search.first.size)

count = 0

directions = (-1..1).to_a.product((-1..1).to_a).reject { _1 == [0, 0] }

search.each_with_index do |row, y|
  row.each_with_index do |char, x|
    next unless char == "X"

    directions.each do |dx, dy|
      next unless range_y.cover?(y + 3 * dy) && range_x.cover?(x + 3 * dx)
      suffix = (1..3).map { search[y + _1 * dy][x + _1 * dx] }.join
      count += 1 if suffix == "MAS"
    end
  end
end

puts count
