#!/usr/bin/awk -f

BEGIN { window = 25 }

function valid(n,   i, j) {
	for (i in prev25) {
		for (j in prev25) {
			if (i == j) {
				continue
			}

			if (prev25[i] == prev25[j]) {
				continue
			}

			if (prev25[i] + prev25[j] == n) {
				return 1
			}
		}
	}

	return 0
}

NR <= window { prev25[NR] = $1 }

NR > window && valid($1) {
	# shuffle previous 25
	delete prev25[NR-window]
	prev25[NR] = $1
	next
}

NR > window {
	print
	exit
}
