#!/bin/bash

before=$(cat input | wc -c)

after=$(sed -e 's/\\\\/S/g' -e 's/\\"/Q/g' -e 's/\\x[[:xdigit:]]\{2\}/X/g' input | wc -c)

echo "Chars before: $before"
echo "Chars after: $after"
echo "Difference: $(( before - after + 2 * $(cat day08_input | wc -l) ))"


