#!/bin/bash

max () {
    local dist
    local max_dist
    for dist; do
        if (( dist > max_dist )); then
            max_dist=$dist
        fi
    done
    echo "$max_dist"
}


while read v t_fly t_rest; do
    speed+=($v)
    flytime+=($t_fly)
    resttime+=($t_rest)
done < <(cut --delimiter ' ' --fields=4,7,14 input)

t=0
t_max=2503
n=${#speed[@]}

for (( i = 0; i < n; ++i )); do
    status[$i]='F'
    timer[$i]=0
    dist[$i]=0
    score[$i]=0
done

while (( t < t_max )); do
    for (( i = 0; i < n; ++i )); do
        (( ++timer[$i] ))
        if [[ ${status[$i]} == F ]]; then
            (( dist[$i] += speed[$i] ))
            if (( timer[$i] == flytime[$i] )); then
                status[$i]='R'
                timer[$i]=0
            fi
        else
            if (( timer[$i] == resttime[$i] )); then
                status[$i]='F'
                timer[$i]=0
            fi
        fi
    done
    (( ++t ))
    furthest=$(max "${dist[@]}")
    for (( i = 0; i < n; ++i )); do
        if (( dist[$i] == furthest )); then
            (( ++score[$i] ))
        fi
    done
done

max_score=$(max "${score[@]}")

echo "Max score after $t_max s: $max_score points"
