#!/usr/bin/awk -f

function bin2dec(n,   l, i, d, fac) {
	l = length(n)
	fac = 1
	for (i = l; i >= 1; --i) {
		d += substr(n, i, 1) * fac
		fac *= 2
	}

	return d
}

{
	gsub(/F/, 0)
	gsub(/B/, 1)
	gsub(/L/, 0)
	gsub(/R/, 1)

	id = bin2dec($0)
	maxid = id > maxid ? id : maxid
}

END { print maxid }
