#!/usr/bin/awk -f

BEGIN { RS = "" }

# Passports with 8 fields are always valid
NF == 8 { ++valid }

# If the cid field is present here, a mandatory field must be missing
NF == 7 {
	for (i = 1; i <= NF; ++i) {
		if (substr($i, 1, 3) == "cid") {
			next
		}
	}

	++valid
}

END { print valid }
