#!/bin/bash

debug=0

min_circumf () {
    local a=$1
    local b=$2
    local c=$3
    local min=$(( 2*a + 2*b ))
    min=$(( 2*a + 2*c < min ? 2*a + 2*c : min ))
    min=$(( 2*b + 2*c < min ? 2*b + 2*c : min ))
    (( debug )) && echo "Minimum: $min" >&2
    echo "$min"
}

regex='([[:digit:]]+)x([[:digit:]]+)x([[:digit:]]+)'
total=0

while read -r line; do
    (( debug )) && echo "Line: $line" >&2
    [[ "$line" =~ $regex ]]
    dim1=${BASH_REMATCH[1]}
    dim2=${BASH_REMATCH[2]}
    dim3=${BASH_REMATCH[3]}
    smallest=$(min_circumf $dim1 $dim2 $dim3)
    (( total += smallest + dim1 * dim2 * dim3 ))
    (( debug )) && echo "Sum: $total" >&2
done < "$1"

echo "Total ribbon needed: $total"
