#!/usr/bin/env bash

# - sort
# - add the socket and the device joltage
# - print a blank line for every time the difference is 3 jolts
# - for each group of consecutive jolts, multiply the number of options by the
#   number of options for that group

sort -n "$1" \
	| awk 'BEGIN { print 0 }; 1; END { print $1 + 3 }' \
	| awk '{ if ($1 - prev == 3) { print "" }; prev = $1; print }' \
	| awk '
		BEGIN {
			RS  = ""
			options = 1
		}

		NF == 3 { options *= 2 }
		NF == 4 { options *= 4 }
		NF == 5 { options *= 7 }

		END { print options }
	'
