#!/usr/bin/awk -f

{ str = $0 }

END {
    len = 272
    while (length(str) < len) {
        cur_len = length(str)
        str = str 0
        for (i = cur_len; i >= 1; --i) {
            next_digit = substr(str, i, 1) == 1 ? 0 : 1
            str = str next_digit
        }
    }

    chksum = substr(str, 1, len)
    while (length(chksum) % 2 == 0) {
        cur_len = length(chksum)
        for (i = 1; i <= cur_len-1; i += 2) {
            next_digit = substr(chksum, i, 1) == substr(chksum, i+1, 1) ? 1 : 0;
            next_chksum = next_chksum next_digit
        }
        chksum = next_chksum
        next_chksum = ""
    }
    print chksum
}
