#!/usr/bin/awk -f

BEGIN { PROCINFO["sorted_in"] = "@ind_num_asc" }

{ elfcount = $0 }

END {
    for (i = 1; i <= elfcount; ++i)
        gifts[i] = 1

    while (1) {
        print "Round " ++round
        for (i in gifts) {
            if (! gifts[i])
                continue
            j = (i == elfcount) ? 1 : i + 1
            while (! gifts[j])
                j = (j == elfcount) ? 1 : j + 1

            gifts[i] += gifts[j]
            delete gifts[j]

            if (gifts[i] == elfcount) {
                print "Elf number " i " gets it all!"
                exit
            }
        }
    }
}
