#!/bin/bash

input=$(< "$1")
floor=0

for (( i = 0; i < ${#input}; ++i )); do
    char=${input:i:1}
    if [[ $char == '(' ]]; then
        (( ++floor ))
    else
        (( --floor ))
    fi
done

echo "Santa should go to floor $floor."
