#!/bin/bash

input=$(< "$1")
floor=0
basement=0

for (( i = 0; i < ${#input}; ++i )); do
    char=${input:i:1}
    if [[ $char == '(' ]]; then
        (( ++floor ))
    else
        (( --floor ))
    fi
    if (( basement == 0  && floor < 0)); then
        basement=$(( i + 1 ))
    fi
        
done

echo "Santa should go to floor $floor."
echo "He first entered the basement after instruction number $basement."
