#!/usr/bin/awk -f

{
    sum = $1
    max = $1
    for (i = 2; i <= NF; ++i) {
        if ($i > max)
            max = $i
        sum += $i
    }
    if (max < sum/2)
        ++valid
}

END { print valid }
