#!/usr/bin/awk -f

{
    # Get next two lines and append to current line
    for (i = 1; i <= 2; ++i) {
        getline nextrow
        $0 = $0 nextrow
    }

    # Triangles are now in fields 1/4/7, 2/5/8 and 3/6/9
    for (i = 1; i <= 3; ++i) {
        sum = $i
        max = $i
        for (j = i+3; j <= i+6; j+=3) {
            if ($j > max)
                max = $j
            sum += $j
        }
        if (max < sum/2)
            ++valid
    }
}

END { print valid }
