#!/bin/bash

sum=0
re='(-?[[:digit:]]+)'

while read -r line; do
    if [[ "$line" =~ $re ]]; then
        (( sum += ${BASH_REMATCH[1]} ))
    fi
done < <(json_pp < input)

echo "Sum of all numbers: $sum"
