#!/bin/bash

re='([[:digit:]]+)\[(.*)\]'

while read -r line; do
    [[ $line =~ $re ]]
    id=${BASH_REMATCH[1]}
    given_chksum=${BASH_REMATCH[2]}

    actual_chksum=$(
        sed 's/-[^-]*$//' <<< "$line" | tr -d '-' | fold -w 1 |
        sort | uniq -c | sed 's/^ *//' | sort -t ' ' -k 1,1nr -k 2,2 |
        head -n 5 | tr -dc 'a-z' | paste -s -d ''
    )

    if [[ $given_chksum == $actual_chksum ]]; then
        (( id_sum += id ))
    fi
done < "$1"

echo "$id_sum"
