#!/usr/bin/env ruby

def evaluate(expr) = expr.scan(/\d+/).map(&:to_i).reduce(:*)

ENABLE = "do()"
DISABLE = "don't()"

memory = File.read(ARGV[0]).strip

total = 0
enabled = true

memory.scan(/mul\(\d{1,3},\d{1,3}\)|do\(\)|don't\(\)/).each do |expr|
  case expr
  when ENABLE
    enabled = true
  when DISABLE
    enabled = false
  else
    total += evaluate(expr) if enabled
  end
end

puts total
