#!/bin/bash

input=$(< "$1")
i=282749

while true; do
    md5=$(printf '%s' "$input$i"  | md5sum)
    if [[ $md5 == 000000* ]]; then
        echo "$input with an attached $i has a hash starting with 000000"
        break
    fi
    (( ++i ))
done
