#!/usr/bin/env ruby

def increasing(levels) = levels.eql?(levels.sort)

def decreasing(levels) = levels.eql?(levels.sort.reverse)

def max_diff(levels)
  levels.each_cons(2).to_a.all? do |a, b|
    diff = (a - b).abs
    (1..3).cover?(diff)
  end
end

file = File.open(ARGV[0])

safe = file.readlines(chomp: true).count do |report|
  levels = report.split.map(&:to_i)
  (increasing(levels) || decreasing(levels)) && max_diff(levels)
end

puts safe
