#!/bin/bash

input='yzbqklnj'
i=282749

while true; do
    md5=$(echo -n "$input$i"  | md5sum)
    if [[ "${md5:0:6}" == '000000' ]]; then
        echo "$input with an attached $i has a hash starting with 000000"
        break
    fi
    (( ++i ))
done
