#!/bin/bash

input='yzbqklnj'
i=1

while true; do
    md5=$(echo -n "$input$i" | md5sum)
    if [[ "${md5:0:5}" == '00000' ]]; then
        echo "$input with an attached $i has a hash starting with 00000"
        break   # Happens at 282749
    fi
    (( ++i ))
done
