#!/usr/bin/awk -f

BEGIN {
    x = 2
    y = 2
}

{
    split($0, dirs, "")
    for (i = 1; i <= length(dirs); ++i) {
        switch (dirs[i]) {
        case "U":
            y = y > 1 ? y - 1 : y
            break
        case "D":
            y = y < 3 ? y + 1 : y
            break
        case "L":
            x = x > 1 ? x - 1 : x
            break
        case "R":
            x = x < 3 ? x + 1 : x
            break
        default:
            print "Illegal direction"
            exit
        }
    }
    code = code (y-1) * 3 + x
}

END { print code }
