#!/usr/bin/env ruby

DIGITS = {
  "one" => 1,
  "two" => 2,
  "three" => 3,
  "four" => 4,
  "five" => 5,
  "six" => 6,
  "seven" => 7,
  "eight" => 8,
  "nine" => 9
}

RE = /(?=(#{DIGITS.keys.join("|")}|\d))/

file = File.open(ARGV[0])

s = file.readlines.sum do |line|
  line.scan(RE).flatten.values_at(0, -1).map do |val|
    DIGITS[val] || val
  end.join.to_i
end

puts s
