#!/usr/bin/env ruby

DIGITS = {
  "one" => 1,
  "two" => 2,
  "three" => 3,
  "four" => 4,
  "five" => 5,
  "six" => 6,
  "seven" => 7,
  "eight" => 8,
  "nine" => 9
}

RE = /one|two|three|four|five|six|seven|eight|nine|\d/

file = File.open(ARGV[0])

s = file.readlines.sum do |line|
  line.scan(RE).values_at(0, -1).tap { |v| p line; p v }.map do |val|
    DIGITS.key?(val) ? DIGITS[val] : val
  end.join("").to_i.tap { |l| p l }
end

puts s
